name: Deploy to CloudHub 2.0 via Exchange

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Deploy to CloudHub 2.0
        run: |
          mvn clean deploy -DmuleDeploy \
            -Danypoint.username="${{ secrets.ANYPOINT_USERNAME }}" \
            -Danypoint.password="${{ secrets.ANYPOINT_PASSWORD }}" \
            -Danypoint.applicationName="sp-mule-demo-api-${{ github.run_number }}" \
            -Danypoint.environment="Sandbox" \
            -Danypoint.target="Cloudhub-US-East-2"
        env:
          MAVEN_OPTS: "-Xmx1024m"