name: Publish to Exchange

on:
    push:
        branches: [ master ]
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v4

            -
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'temurin'

            -
                name: Build package
                run: mvn clean package -DskipTests

            -
                name: Publish to Anypoint Exchange
    run: |
        mvn org.mule.tools.maven:exchange-mule-maven-plugin:0.0.21:exchange-deploy \
          -Danypoint.username="${{ secrets.ANYPOINT_USERNAME }}" \
          -Danypoint.password="${{ secrets.ANYPOINT_PASSWORD }}" \
          -Danypoint.orgId="961cedea-7d40-4e76-8cbb-dac76753c5c8" \
          -DbusinessGroupId="cts" \
          -DassetGroupId="cts" \
          -DassetArtifactId="hello-world-api" \
          -DassetVersion="1.0.0" \
          -DassetPackaging="mule-application" \
          -Dname="hello-world-api" \
          -Ddescription="Hello World API"
