name: Build & Deploy (manual commands)

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Publish to Exchange (skip tests)
        run: |
          mvn clean deploy -DskipTests \
            -Danypoint.username="shyanypoint092625" \
            -Danypoint.password="Dingari007#"

      - name: Wait 60 seconds before deploy
        run: sleep 60

      - name: Deploy to CloudHub 2.0
        run: |
          mvn clean package mule:deploy -DmuleDeploy \
            -Danypoint.username="shyanypoint092625" \
            -Danypoint.password="Dingari007#" \
            -Danypoint.applicationName="sp-mule-demo-api-local" \
            -Danypoint.environment="Sandbox" \
            -Danypoint.target="Cloudhub-US-East-2"
