name: Deploy to CloudHub 2.0 via Exchange

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Configure Maven Settings
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml << EOF
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 
                                        http://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>anypoint-exchange-v3</id>
                <username>shyanypoint092625</username>
                <password>Dingari007#</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Publish to Exchange
        run: mvn clean deploy -DskipTests
        env:
          MAVEN_OPTS: "-Xmx1024m"

      - name: Wait for Exchange Indexing
        run: |
          echo "Waiting for Exchange to index the published artifact..."
          sleep 60
          echo "Exchange indexing wait completed"

      - name: Verify Exchange Publication
        run: |
          echo "Verifying publication in Exchange..."
          echo "Artifact should be available at:"
          echo "https://anypoint.mulesoft.com/exchange/961cedea-7d40-4e76-8cbb-dac76753c5c8/sp-mule-demo-api/"

      - name: Deploy to CloudHub 2.0
        run: |
          mvn clean package mule:deploy -DmuleDeploy \
            -Danypoint.username="shyanypoint092625" \
            -Danypoint.password="Dingari007#" \
            -Danypoint.applicationName="sp-mule-demo-api-local" \
            -Danypoint.environment="Sandbox" \
            -Danypoint.target="Cloudhub-US-East-2"
        env:
          MAVEN_OPTS: "-Xmx1024m"

      - name: Deployment Summary
        run: |
          echo "Deployment completed successfully!"
          echo "Application Name: sp-mule-demo-api-local"
          echo "Environment: Sandbox"
          echo "Target: Cloudhub-US-East-2"