name: Publish to Exchange (only)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build package
        run: mvn -B -U -e clean package -DskipTests

      - name: Show where publish will go
        run: |
          echo "Repo: $(mvn -q help:evaluate -Dexpression=project.distributionManagement.repository.url -DforceStdout)"
          echo "GAV:  $(mvn -q help:evaluate -Dexpression=project.groupId -DforceStdout):$(mvn -q help:evaluate -Dexpression=project.artifactId -DforceStdout):$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)"

      - name: Publish to Anypoint Exchange
        run: |
          mvn -B -U -e org.mule.tools.maven:exchange-mule-maven-plugin:0.0.21:exchange-deploy \
            -Danypoint.username="${{ secrets.ANYPOINT_USERNAME }}" \
            -Danypoint.password="${{ secrets.ANYPOINT_PASSWORD }}" \
            -Danypoint.orgId="${{ secrets.ANYPOINT_ORG_ID }}"
