name: Publish to Exchange (cts)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build package
        run: mvn clean package -DskipTests

      - name: Publish to Anypoint Exchange (cts business group)
        run: |
          mvn org.mule.tools.maven:exchange-mule-maven-plugin:0.0.21:exchange-deploy \
            -Danypoint.username="${{ secrets.ANYPOINT_USERNAME }}" \
            -Danypoint.password="${{ secrets.ANYPOINT_PASSWORD }}" \
            -Danypoint.orgId="961cedea-7d40-4e76-8cbb-dac76753c5c8" \
            -DbusinessGroupId="cts" \
            -DassetGroupId="cts" \
            -DassetArtifactId="sp-mule-demo-api" \
            -DassetVersion="1.0.0" \
            -DassetPackaging="mule-application" \
            -Dname="SP Mule Demo API" \
            -Ddescription="Shyam Prasad MuleSoft Demo API for CI/CD pipeline"

      - name: Check Exchange API directly
        run: |
          echo "Checking if asset exists via Exchange API..."
          curl -s -u "${{ secrets.ANYPOINT_USERNAME }}:${{ secrets.ANYPOINT_PASSWORD }}" \
            "https://anypoint.mulesoft.com/exchange/api/v2/organizations/961cedea-7d40-4e76-8cbb-dac76753c5c8/assets?search=sp-mule-demo-api" \
            | jq '.' || echo "Asset not found in Exchange API"

      - name: List all assets in cts business group
        run: |
          echo "Listing all assets in organization..."
          curl -s -u "${{ secrets.ANYPOINT_USERNAME }}:${{ secrets.ANYPOINT_PASSWORD }}" \
            "https://anypoint.mulesoft.com/exchange/api/v2/organizations/961cedea-7d40-4e76-8cbb-dac76753c5c8/assets?limit=50" \
            | jq '.[] | {groupId, artifactId, version, name}' || echo "Failed to list assets"