name: Deploy to CloudHub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        
    - name: Build with Maven
      run: mvn clean package
      
    - name: Deploy to CloudHub 2.0
      run: |
        mvn clean deploy -DmuleDeploy \
          -Danypoint.username="${{ secrets.ANYPOINT_USERNAME }}" \
          -Danypoint.password="${{ secrets.ANYPOINT_PASSWORD }}" \
          -Danypoint.applicationName="hello-world-api-${{ github.run_number }}" \
          -Danypoint.environment="Sandbox" \
          -Danypoint.target="Cloudhub-US-East-2"